<a href="https://colab.research.google.com/github/Priyanshu45132/JSR/blob/main/AQI%202.0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import warnings
import pickle

In [2]:
warnings.filterwarnings("ignore")

In [5]:
data = pd.read_csv("Forest_fire.csv")
data = np.array(data)

In [6]:
X = data[1:, 1:-1]
y = data[1:, -1]
y = y.astype('int')
X = X.astype('int')

In [7]:
print(X,y)

[[ 50  30  10]
 [ 10  20  70]
 [ 60  45  70]
 [ 30  48  10]
 [ 50  15  30]
 [  5  35  35]
 [  5  20  70]
 [ 60  32  19]
 [ 30  50  45]
 [ 40  55  80]
 [ 30  39 100]
 [ 10  12  12]
 [ 20  23  23]
 [ 60  34  15]
 [ 80   4  68]
 [ 25  56  79]
 [ 12  45  90]
 [ 28  43  15]
 [ 26   0  32]
 [ 32  37  21]
 [ 45  48  12]
 [ 56  15  65]
 [ 67  45  33]
 [ 78  49   8]
 [ 89  45  18]
 [ 21  12  44]
 [ 11  20  59]
 [  1  32  70]
 [  5  20  45]
 [ 42  43  20]
 [ 32  60  30]
 [  5  15   5]
 [ 20  30   5]
 [ 30  51   2]
 [ 60  60  10]
 [ 10  10  60]
 [  0  30   0]
 [ 45  45  15]] [1 0 1 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0 0
 1]


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
log_reg = LogisticRegression()


In [9]:
log_reg.fit(X_train, y_train)

LogisticRegression()

In [10]:
inputt=[int(x) for x in "45 32 60".split(' ')]
final=[np.array(inputt)]


In [11]:
b = log_reg.predict_proba(final)

In [12]:
pickle.dump(log_reg,open('model.pkl','wb'))
model=pickle.load(open('model.pkl','rb'))